AWSTemplateFormatVersion: 2010-09-09
Description: Create the Cross-Account IAM Prowler Role

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EC2 Settings
        Parameters:
          - Ec2Account
          - Ec2Role
      - Label:
          default: S3 Settings
        Parameters:
          - S3
      - Label:
          default: CrossAccount Role
        Parameters:
          - CrossAccountRole

Parameters:
  S3:
    Type: String
    Description: Enter S3 Bucket to grant rights to EC2 Instance
    Default: prowler-417425889548-us-east-1
  Ec2Account:
    Type: String
    Description: Enter AWS Account Number where EC2 Instance resides
    AllowedPattern: ^\d{12}$
    ConstraintDescription: An AWS Account Number must be a 12 digit numeric string.
    Default: 544425379660
  Ec2Role:
    Type: String
    Description: Enter Instance Role given to EC2 Instance (to grant sts:AssumeRole rights).
    Default: ProwlerEC2-Role
  CrossAccountRole:
    Type: String
    Description: Enter Name for CrossAccount Role to be created
    Default: ProwlerXA-Role

Resources:
  ProwlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CrossAccountRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                # - !Sub arn:${AWS::Partition}:iam::${Ec2Account}:role/${Ec2Role}
                - !Sub arn:${AWS::Partition}:iam::${Ec2Account}:root
            Action:
              - sts:AssumeRole
            Condition:
              StringLike:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${Ec2Account}:role/${Ec2Role}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/SecurityAudit
        - !Sub arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess
      Policies:
        - PolicyName: Prowler-Additions-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowMoreReadForProwler
                Effect: Allow
                Resource: "*"
                Action:
                  - access-analyzer:List*
                  - apigateway:Get*
                  - apigatewayv2:Get*
                  - aws-marketplace:ViewSubscriptions
                  - dax:ListTables
                  - ds:ListAuthorizedApplications
                  - ds:DescribeRoles
                  - ec2:GetEbsEncryptionByDefault
                  - ecr:Describe*
                  - lambda:GetAccountSettings
                  - lambda:GetFunctionConfiguration
                  - lambda:GetLayerVersionPolicy
                  - lambda:GetPolicy
                  - opsworks-cm:Describe*
                  - opsworks:Describe*
                  - secretsmanager:ListSecretVersionIds
                  - sns:List*
                  - sqs:ListQueueTags
                  - states:ListActivities
                  - support:Describe*
                  - tag:GetTagKeys
        - PolicyName: Prowler-S3-Reports
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowGetPutListObject
                Effect: Allow
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${S3}
                  - !Sub arn:${AWS::Partition}:s3:::${S3}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Prowler requires these rights to perform its Security Assessment."
          - id: W28
            reason: "Using a defined Role Name."

Outputs:
  ProwlerCrossAccountRole:
    Description: Prowler CrossAccount Role
    Value: !Ref CrossAccountRole
