services:
  restful-api:
    build:
      dockerfile: Dockerfile
    image: prowler-restful-api
    ports:
      - "8000:8000"
    profiles:
      - prod

  restful-api-dev:
    build:
      dockerfile: Dockerfile
      target: dev
    image: prowler-restful-api-dev
    ports:
      - "8080:8000"
    volumes:
      - "./src/backend:/home/prowler/backend"
      - "./pyproject.toml:/home/prowler/pyproject.toml"
    profiles:
      - dev
