services:
  restful-api:
    build:
      dockerfile: Dockerfile
    image: prowler-restful-api
    env_file:
      - path: ./.env
        required: false
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    profiles:
      - prod
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - "../docker-entrypoint.sh"
      - "prod"

  restful-api-dev:
    build:
      dockerfile: Dockerfile
      target: dev
    image: prowler-restful-api-dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.devel
      - DJANGO_LOGGING_FORMATTER=human_readable
    env_file:
      - path: ./.env
        required: false
    ports:
      - "${DJANGO_PORT:-8080}:${DJANGO_PORT:-8080}"
    volumes:
      - "./src/backend:/home/prowler/backend"
      - "./pyproject.toml:/home/prowler/pyproject.toml"
    profiles:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - "../docker-entrypoint.sh"
      - "dev"

  postgres:
    image: postgres:16.3-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    hostname: "postgres-db"
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER:-prowler}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-S3cret}
      - POSTGRES_DB=${POSTGRES_DB:-prowler_db}
    env_file:
      - path: ./.env
        required: false
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_ADMIN_USER:-prowler} -d ${POSTGRES_DB:-prowler_db}'"]
      interval: 5s
      timeout: 5s
      retries: 5
