[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Prowler Team"]
description = "Prowler's RESTful API (Django/DRF)"
license = "AGPL-3.0"
name = "prowler-rest-api"
package-mode = false
version = "1.0.0"

[tool.poetry.dependencies]
django = "5.0.7"
django-cors-headers = "4.4.0"
django-guid = "3.5.0"
djangorestframework = "3.15.2"
drf-spectacular = "0.27.2"
gunicorn = "22.0.0"
psycopg2-binary = "2.9.9"
python = "^3.12"

[tool.poetry.group.dev.dependencies]
bandit = "1.7.9"
coverage = "7.5.4"
docker = "7.1.0"
freezegun = "1.5.1"
mypy = "1.10.1"
pylint = "3.2.5"
pytest = "8.2.2"
pytest-cov = "5.0.0"
pytest-django = "4.8.0"
pytest-env = "1.1.3"
pytest-randomly = "3.15.0"
pytest-xdist = "3.6.1"
ruff = "0.5.0"
safety = "3.2.3"
vulture = "2.11"
